name: Set Masked KV Secret 

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      kv_name:
        description: Name of the Vault
        required: true
      secret_name:
        description: Name of the secret
        required: true
      secret_value:
        description: Value of the secret
        required: true
        
jobs:
  set-secret-kv:
    name: "Set Secret:"
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_NONPROD }}
        
    - name: Test masking inputs
      id: add_mask
      run: |
        INP_SECRET=$(jq -r '.inputs.secret_value' $GITHUB_EVENT_PATH)
        echo $INP_SECRET

