name: Set Masked KV Secret 

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      kv_name:
        description: Name of the Vault
        required: true
      secret_name:
        description: Name of the secret
        required: true
      secret_value:
        description: Value of the secret
        required: true
        
jobs:
  set-secret-kv:
    name: "Set Secret:"
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_NONPROD }}
        
    - name: Mask inputs
      id: add_mask
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_NONPROD }}
      run: |
        INP_SECRET=$(jq -r '.inputs.secret_value' $GITHUB_EVENT_PATH)
        echo ::add-mask::$INP_SECRET
        echo ::set-output name=secret::$INP_SECRET
        SP_APPID=$(echo $AZURE_CREDENTIALS | jq -e -r 'select(.clientId != null) | .clientId')
        echo ::set-output name=clientid::$SP_APPID
        
    - name: Create KV Secret
      uses: azure/CLI@v1
      with:
        inlineScript: |
          KV_NAME=${{ github.event.inputs.kv_name }}
          SECRET_NAME=${{ github.event.inputs.secret_name }}
          az keyvault set-policy -n $KV_NAME --secret-permissions get list set --spn ${{ steps.add_mask.outputs.clientid }}
          TEST=$(az keyvault secret set --name $SECRET_NAME --vault-name $KV_NAME --value ${{ steps.add_mask.outputs.secret }})


