name: Set Masked KV Secret 

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      secret_name:
        description: Name of the secret
        required: true
        
jobs:
  set-secret-kv:
    name: "Set Secret:"
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_NONPROD }}
        
    - name: Get client ID
      id: add_mask
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_NONPROD }}
      run: |
        SP_APPID=$(echo $AZURE_CREDENTIALS | jq -e -r 'select(.clientId != null) | .clientId')
        SP_SUBSCRIPTION_ID=$(echo $AZURE_CREDENTIALS | jq -e -r 'select(.subscriptionId != null) | .subscriptionId')
        echo ::set-output name=clientid::$SP_APPID
        echo ::set-output name=subscriptionid::$SP_SUBSCRIPTION_ID
        
    - name: Create KV Secret
      uses: azure/CLI@v1
      with:
        inlineScript: |
          SECRET_NAME=${{ github.event.inputs.secret_name }}
          SECRET_VALUE=$(openssl rand -base64 32)
          KV_NAME=$(az keyvault list --resource-type vault --subscription ${{ steps.add_mask.outputs.subscriptionid }} --query [].name -o tsv)
          echo $KV_NAME
          az keyvault set-policy -n $KV_NAME --secret-permissions get list set --spn ${{ steps.add_mask.outputs.clientid }}
          TEST=$(az keyvault secret set --name $SECRET_NAME --vault-name $KV_NAME --value $SECRET_VALUE)


