name: Set KV Secret 

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      kv_name:
        description: Name of the Vault
        required: true
      secret_name:
        description: Name of the secret
        required: true
      secret_value:
        description: Value of the secret
        required: true
env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_NONPROD }}
  KV_NAME: ${{ github.event.inputs.kv_name }}
  SECRET_NAME: ${{ github.event.inputs.secret_name }}
  SECRET_VALUE: ${{ github.event.inputs.secret_value }}
  
jobs:
  set-secret-kv:
    name: "Set Secret:"
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_NONPROD }}
        
    - name: Create KV Secret
      uses: azure/CLI@v1
      with:
        inlineScript: |
          #SP_APPID=$(echo $AZURE_CREDENTIALS | jq -e -r 'select(.clientId != null) | .clientId')
          az keyvault set-policy -n $KV_NAME --secret-permissions get list set --spn $SP_APPID
          az keyvault secret set --name $SECRET_NAME --vault-name $KV_NAME --value $SECRET_VALUE
