name: Set KV Secret 

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      kv_name:
        description: Name of the Vault
        required: true
      secret_name:
        description: Name of the secret
        required: true
      secret_value:
        description: Value of the secret
        required: true
      CREDENTIALS:
        description: Value of the secret
        required: true
env:
  AZURE_CREDENTIALS: ${{ github.event.inputs.CREDENTIALS }}
  KV_NAME: ${{ github.event.inputs.kv_name }}
  SECRET_NAME: ${{ github.event.inputs.secret_name }}
  SECRET_VALUE: ${{ github.event.inputs.secret_value }}
  
jobs:
  set-secret-kv:
    name: "Set Secret:"
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_NONPROD }}
        
    # Login to ACR   
    - name: Login to ACR
      env:
        AZURE_CREDENTIALS: ${{ inputs.AZURE_CREDENTIALS_NONPROD }}
      run: |
        SP_APPID=$(echo $AZURE_CREDENTIALS | jq -e -r 'select(.subscriptionId != null) | .subscriptionId')
        echo $SP_APPID
      shell: bash
      
    - name: Create KV Secret
      uses: azure/CLI@v1
      with:
        inlineScript: |
          SP_APPID=$(echo $AZURE_CREDENTIALS | jq -e -r 'select(.subscriptionId != null) | .subscriptionId')
          echo $SP_APPID
          #SP_APPID=$(echo $AZURE_CREDENTIALS | jq -e -r 'select(.clientId != null) | .clientId')
          #az keyvault set-policy -n $KV_NAME --secret-permissions get list set --spn $SP_APPID
          #az keyvault secret set --name $SECRET_NAME --vault-name $KV_NAME --value $SECRET_VALUE
