name: Set KV Secret 

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      kv_name:
        description: Name of the Vault
        required: true
      secret_name:
        description: Name of the secret
        required: true
      secret_value:
        description: Value of the secret
        required: true

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_NONPROD }}
  
jobs:
  set-secret-kv:
    name: "Set Secret:"
    runs-on: ubuntu-latest
    steps:
    #- name: Azure Login
    #  uses: azure/login@v1
    #  with:
    #    creds: ${{ secrets.AZURE_CREDENTIALS_NONPROD }}
      
    - name: Create KV Secret
      uses: azure/CLI@v1
      with:
        inlineScript: |
          AZURE_CREDENTIALS_TEST=${{ env.AZURE_CREDENTIALS }}
          echo $AZURE_CREDENTIALS_TEST
          KV_NAME=${{ github.event.inputs.kv_name }}
          echo $KV_NAME
          SECRET_NAME=${{ github.event.inputs.secret_name }}
          echo $SECRET_NAME
          SECRET_VALUE=${{ github.event.inputs.secret_value }}
          echo $SECRET_VALUE

